"""
Enrich defect_library with item-specific suggestions for items that only have category fallbacks.
241 items across 7 areas, 10 categories.
Run on Render Console: python3 scripts/enrich_defect_library.py
"""
import sqlite3
import uuid
from datetime import datetime

conn = sqlite3.connect('/var/data/inspections.db')
cur = conn.cursor()

TENANT = 'MONOGRAPH'
now = datetime.utcnow().isoformat()

# Mapping: (item_description_lower, category_name) -> list of defect descriptions
# Where item appears in multiple categories, we provide category-appropriate descriptions
ITEM_DEFECTS = {
    # === DOORS ===
    ('hinges', 'DOORS'): [
        'Sand in hinges',
        'Hinge pin loose',
        'Hinges misaligned',
        'Hinge screws stripped',
        'Hinge leaves bent',
    ],
    ('finish', 'DOORS'): [
        'Damaged paint as indicated',
        'Paint runs/drips on door',
        'Scratches on door finish',
        'Door finish uneven/patchy',
        'Paint overspray on frame',
    ],
    ('striker plate', 'DOORS'): [
        'Striker plate misaligned',
        'Striker plate loose',
        'Striker plate not installed',
        'Striker plate screws missing',
    ],
    ('handle', 'DOORS'): [
        'Handle loose',
        'Handle scratched/damaged',
        'Handle not aligned',
        'Handle stiff to operate',
    ],
    ('lockset - cylinder and thumb turn', 'DOORS'): [
        'Lockset not operating smoothly',
        'Cylinder loose',
        'Thumb turn stiff',
        'Lockset installed upside down',
        'Key does not turn',
    ],
    ('kickplate', 'DOORS'): [
        'Kickplate scratched',
        'Kickplate loose',
        'Kickplate not installed',
        'Kickplate dented',
    ],
    ('master key', 'DOORS'): [
        'Master key does not work',
        'Master key not supplied',
        'Key does not turn in lock',
    ],
    ('door closer', 'DOORS'): [
        'Door closer not closing fully',
        'Door closer too fast',
        'Door closer too slow',
        'Door closer leaking oil',
        'Door closer arm loose',
    ],
    ('unit signage', 'DOORS'): [
        'Signage not installed',
        'Signage incorrect unit number',
        'Signage damaged/scratched',
        'Signage not level',
    ],
    ('signage', 'DOORS'): [
        'Signage not installed',
        'Signage incorrect',
        'Signage damaged/scratched',
        'Signage not level',
    ],
    ('face brick sill', 'DOORS'): [
        'Brick sill cracked',
        'Brick sill mortar missing',
        'Brick sill not level',
        'Brick sill stained',
    ],
    ('soft joint between tile and brick', 'DOORS'): [
        'Soft joint missing',
        'Soft joint cracked',
        'Soft joint uneven',
        'Sealant discoloured',
    ],
    ('finished all round', 'DOORS'): [
        'Gaps in finish around frame',
        'Paint missing on edges',
        'Finish not consistent all round',
        'Touch-up needed on reveal',
    ],
    ('paint on outside - lemon rind', 'DOORS'): [
        'Paint colour mismatch',
        'Paint runs/drips',
        'Paint scratched/chipped',
        'Paint finish uneven',
    ],
    ('paint on outside - glorious gold', 'DOORS'): [
        'Paint colour mismatch',
        'Paint runs/drips',
        'Paint scratched/chipped',
        'Paint finish uneven',
    ],
    ('paint on outside - yellow balloon', 'DOORS'): [
        'Paint colour mismatch',
        'Paint runs/drips',
        'Paint scratched/chipped',
        'Paint finish uneven',
    ],
    ('residence lock handle', 'DOORS'): [
        'Handle loose',
        'Handle not operating smoothly',
        'Handle scratched/damaged',
        'Handle rose plate loose',
    ],
    ('key - a', 'DOORS'): [
        'Key does not work',
        'Key not supplied',
        'Key stiff in lock',
    ],
    ('key - b', 'DOORS'): [
        'Key does not work',
        'Key not supplied',
        'Key stiff in lock',
    ],
    ('key - c', 'DOORS'): [
        'Key does not work',
        'Key not supplied',
        'Key stiff in lock',
    ],
    ('key - d', 'DOORS'): [
        'Key does not work',
        'Key not supplied',
        'Key stiff in lock',
    ],
    ('installation', 'DOORS'): [
        'Door not plumb',
        'Door not closing properly',
        'Gap under door too large',
        'Door rubbing on frame',
    ],
    ('operation', 'DOORS'): [
        'Door does not close properly',
        'Door sticking',
        'Door does not latch',
        'Door swings open on its own',
    ],
    ('frame & coating', 'DOORS'): [
        'Frame coating scratched',
        'Frame coating peeling',
        'Frame not plumb',
        'Frame coating colour mismatch',
    ],

    # === WALLS ===
    ('tile trim at window 1a', 'WALLS'): [
        'Tile trim loose',
        'Tile trim gap at corner',
        'Tile trim chipped',
        'Tile trim not flush with tile',
    ],
    ('splash back wrap at sink', 'WALLS'): [
        'Splash back tiles loose',
        'Splash back grout cracked',
        'Splash back not sealed at edges',
        'Splash back tile chipped',
    ],
    ('tile trim at top and side', 'WALLS'): [
        'Tile trim loose',
        'Tile trim not level',
        'Tile trim gap visible',
        'Tile trim chipped/damaged',
    ],
    ('grout dove grey', 'WALLS'): [
        'Inconsistent grout colour',
        'Grout missing between tiles',
        'Grout cracked',
        'Grout stained',
    ],
    ('chipped/broken/hollow tiles', 'WALLS'): [
        'Tile chipped as indicated',
        'Tile cracked',
        'Hollow tile detected',
        'Tile broken - needs replacement',
    ],
    ('smooth plaster', 'WALLS'): [
        'Plaster cracked',
        'Plaster uneven/rough',
        'Plaster bubbling',
        'Nail pops visible',
        'Plaster damaged as indicated',
    ],
    ('paint - divina', 'WALLS'): [
        'Paint finish uneven',
        'Paint runs/drips',
        'Paint colour mismatch',
        'Paint scratched/scuffed',
    ],
    ('paint - lemon rind', 'WALLS'): [
        'Paint finish uneven',
        'Paint runs/drips',
        'Paint colour mismatch',
        'Paint scratched/scuffed',
    ],
    ('paint - yellow balloon', 'WALLS'): [
        'Paint finish uneven',
        'Paint runs/drips',
        'Paint colour mismatch',
        'Paint scratched/scuffed',
    ],
    ('plaster recess at ceiling', 'WALLS'): [
        'Plaster recess cracked',
        'Plaster recess uneven',
        'Shadow line not straight',
        'Plaster recess needs sanding',
    ],

    # === WINDOWS ===
    ('hinges', 'WINDOWS'): [
        'Window hinge stiff',
        'Window hinge loose',
        'Window hinge misaligned',
        'Hinge screws missing',
    ],
    ('operation', 'WINDOWS'): [
        'Window does not open/close properly',
        'Window handle stiff',
        'Window does not lock',
        'Window rattles when closed',
    ],
    ('frame & coating', 'WINDOWS'): [
        'Frame coating scratched',
        'Frame coating peeling',
        'Frame not sealed properly',
        'Frame coating discoloured',
    ],
    ('burglar bars', 'WINDOWS'): [
        'Burglar bars not installed',
        'Burglar bars loose',
        'Burglar bars paint scratched',
        'Burglar bars not aligned',
    ],
    ('gaskets', 'WINDOWS'): [
        'Gasket loose/displaced',
        'Gasket missing',
        'Gasket torn/damaged',
        'Gasket not seated properly',
    ],
    ('sill', 'WINDOWS'): [
        'Window sill cracked',
        'Window sill not level',
        'Window sill stained',
        'Window sill sealant missing',
    ],

    # === FLOOR ===
    ('floor tile set out', 'FLOOR'): [
        'Tile layout not centred',
        'Tile cuts uneven at edges',
        'Tile spacing inconsistent',
        'Tile not level/lippage',
    ],
    ('tile skirting', 'FLOOR'): [
        'Skirting tile loose',
        'Skirting tile chipped',
        'Skirting grout missing',
        'Skirting tile not aligned',
    ],
    ('chipped/broken/hollow tiles', 'FLOOR'): [
        'Tile chipped as indicated',
        'Tile cracked',
        'Hollow tile detected',
        'Tile broken - needs replacement',
    ],
    ('dark grey grout in shower', 'FLOOR'): [
        'Grout colour inconsistent',
        'Grout missing between tiles',
        'Grout cracked in shower',
        'Grout stained',
    ],
    ('fall to trap', 'FLOOR'): [
        'Water not draining to trap',
        'Ponding water in shower',
        'Fall insufficient',
        'Fall direction incorrect',
    ],
    ('grout dove grey', 'FLOOR'): [
        'Inconsistent grout colour',
        'Grout missing between tiles',
        'Grout cracked',
        'Grout stained',
    ],

    # === CEILING ===
    ('paint-orchid bay', 'CEILING'): [
        'Ceiling paint uneven',
        'Ceiling paint runs/drips',
        'Ceiling paint scratched',
        'Ceiling needs touch-up',
    ],
    ('paint - divina', 'CEILING'): [
        'Ceiling paint uneven',
        'Ceiling paint runs/drips',
        'Ceiling paint colour mismatch',
        'Ceiling needs touch-up',
    ],
    ('paint - lemon rind', 'CEILING'): [
        'Ceiling paint uneven',
        'Ceiling paint runs/drips',
        'Ceiling paint colour mismatch',
        'Ceiling needs touch-up',
    ],
    ('paint - glorious gold', 'CEILING'): [
        'Ceiling paint uneven',
        'Ceiling paint runs/drips',
        'Ceiling paint colour mismatch',
        'Ceiling needs touch-up',
    ],
    ('paint - yellow balloon', 'CEILING'): [
        'Ceiling paint uneven',
        'Ceiling paint runs/drips',
        'Ceiling paint colour mismatch',
        'Ceiling needs touch-up',
    ],
    ('plaster recess', 'CEILING'): [
        'Plaster recess cracked',
        'Plaster recess uneven',
        'Shadow line not straight',
        'Plaster recess needs sanding',
    ],

    # === ELECTRICAL ===
    ('fluorescent led x 2 bulbs', 'ELECTRICAL'): [
        'Light not working',
        'Light flickering',
        'Bulb missing',
        'Light fitting loose',
    ],
    ('fridge double plug', 'ELECTRICAL'): [
        'Plug not working',
        'Plug plate loose',
        'Plug plate scratched/damaged',
        'Plug wired incorrectly',
    ],
    ('stove isolator', 'ELECTRICAL'): [
        'Isolator not working',
        'Isolator switch stiff',
        'Isolator plate loose',
        'Isolator wired incorrectly',
    ],
    ('double plug below db', 'ELECTRICAL'): [
        'Plug not working',
        'Plug plate loose',
        'Plug plate scratched/damaged',
        'Plug wired incorrectly',
    ],
    ('double plug at w1a', 'ELECTRICAL'): [
        'Plug not working',
        'Plug plate loose',
        'Plug plate scratched/damaged',
    ],
    ('single light switch by d1', 'ELECTRICAL'): [
        'Switch not working',
        'Switch plate loose',
        'Switch plate scratched/damaged',
    ],
    ('operation', 'ELECTRICAL'): [
        'Not operating correctly',
        'Tripping frequently',
        'No power to unit',
        'Intermittent power',
    ],
    ('control panel', 'ELECTRICAL'): [
        'Panel not responding',
        'Panel display faulty',
        'Panel buttons not working',
        'Panel not installed',
    ],
    ('study desk light x 1 bulb', 'ELECTRICAL'): [
        'Light not working',
        'Light fitting loose',
        'Bulb missing',
        'Light flickering',
    ],
    ('ceiling mounted light x 2 bulbs', 'ELECTRICAL'): [
        'Light not working',
        'Light fitting loose',
        'Bulb missing',
        'Light flickering',
    ],
    ('ceiling mounted light x 1 bulbs', 'ELECTRICAL'): [
        'Light not working',
        'Light fitting loose',
        'Bulb missing',
        'Light flickering',
    ],
    ('combination plug wall 03', 'ELECTRICAL'): [
        'Plug not working',
        'Plug plate loose',
        'USB port not working',
        'Plug plate scratched',
    ],
    ('combination plug wall 05', 'ELECTRICAL'): [
        'Plug not working',
        'Plug plate loose',
        'USB port not working',
        'Plug plate scratched',
    ],
    ('combination plug wall 22', 'ELECTRICAL'): [
        'Plug not working',
        'Plug plate loose',
        'USB port not working',
        'Plug plate scratched',
    ],
    ('combination plug wall 19', 'ELECTRICAL'): [
        'Plug not working',
        'Plug plate loose',
        'USB port not working',
        'Plug plate scratched',
    ],
    ('panel heater plug wall 07', 'ELECTRICAL'): [
        'Plug not working',
        'Plug plate loose',
        'Plug wired incorrectly',
    ],
    ('panel heater plug wall 21', 'ELECTRICAL'): [
        'Plug not working',
        'Plug plate loose',
        'Plug wired incorrectly',
    ],
    ('panel heater plug wall 20', 'ELECTRICAL'): [
        'Plug not working',
        'Plug plate loose',
        'Plug wired incorrectly',
    ],
    ('double plug on 09 wall', 'ELECTRICAL'): [
        'Plug not working',
        'Plug plate loose',
        'Plug plate scratched/damaged',
    ],
    ('single light switch on 11 wall', 'ELECTRICAL'): [
        'Switch not working',
        'Switch plate loose',
        'Switch plate scratched',
    ],
    ('double light switch on wall 02', 'ELECTRICAL'): [
        'Switch not working',
        'Switch plate loose',
        'Switch wired incorrectly',
    ],
    ('double light switch on wall 08', 'ELECTRICAL'): [
        'Switch not working',
        'Switch plate loose',
        'Switch wired incorrectly',
    ],
    ('double light switch on wall 24', 'ELECTRICAL'): [
        'Switch not working',
        'Switch plate loose',
        'Switch wired incorrectly',
    ],
    ('double light switch on wall 17', 'ELECTRICAL'): [
        'Switch not working',
        'Switch plate loose',
        'Switch wired incorrectly',
    ],

    # === PLUMBING ===
    ('installation', 'PLUMBING'): [
        'Arm cover plate loose',
        'Rose cover plate loose',
        'Fitting not secure',
        'Installation not plumb',
        'Sealant missing around base',
    ],
    ('operation', 'PLUMBING'): [
        'Tap dripping/leaking',
        'Drain blocked/slow',
        'Flush not working properly',
        'Water pressure low',
    ],
    ('plugs', 'PLUMBING'): [
        'Plug missing',
        'Plug does not seal',
        'Plug chain missing',
        'Plug damaged',
    ],
    ('plug', 'PLUMBING'): [
        'Plug missing',
        'Plug does not seal',
        'Plug chain missing',
        'Plug damaged',
    ],
    ('p-trap', 'PLUMBING'): [
        'P-trap leaking',
        'P-trap loose',
        'P-trap not installed',
        'P-trap connection not sealed',
    ],
    ('hot water', 'PLUMBING'): [
        'No hot water',
        'Hot water temperature too low',
        'Hot water takes too long',
        'Hot water on wrong side',
    ],
    ('cold water', 'PLUMBING'): [
        'No cold water',
        'Cold water on wrong side',
        'Water pressure low',
        'Tap dripping',
    ],
    ('stability plate', 'PLUMBING'): [
        'Stability plate loose',
        'Stability plate not installed',
        'Stability plate misaligned',
    ],
    ('seat', 'PLUMBING'): [
        'Toilet seat loose',
        'Toilet seat scratched',
        'Toilet seat hinges broken',
        'Toilet seat not aligned',
    ],
    ('control panel', 'PLUMBING'): [
        'Panel not responding',
        'Panel buttons not working',
        'Panel display faulty',
        'Panel not installed',
    ],

    # === JOINERY ===
    ('fixing to wall', 'JOINERY'): [
        'Unit not secured to wall',
        'Wall plugs pulling out',
        'Unit not level',
        'Gap between unit and wall',
    ],
    ('finish', 'JOINERY'): [
        'Paint on joinery finish',
        'Finish scratched/damaged',
        'Finish peeling/bubbling',
        'Finish colour inconsistent',
        'Finish needs cleaning',
    ],
    ('handles', 'JOINERY'): [
        'Handle loose',
        'Handle scratched',
        'Handle missing',
        'Handle not aligned',
    ],
    ('top', 'JOINERY'): [
        'Top scratched/damaged',
        'Top not level',
        'Top edge chipped',
        'Top sealant missing at wall',
    ],
    ('layout', 'JOINERY'): [
        'Doors not aligned',
        'Drawers not aligned',
        'Shelves not level',
        'Unit not square',
    ],
    ('carcass', 'JOINERY'): [
        'Carcass damaged',
        'Carcass not square',
        'Carcass edge chipped',
        'Carcass backing loose',
    ],
    ('hinges', 'JOINERY'): [
        'Hinge loose',
        'Door not closing properly',
        'Hinge adjustment needed',
        'Soft close not working',
    ],
    ('installation', 'JOINERY'): [
        'Unit not level',
        'Unit not plumb',
        'Unit not secured properly',
        'Installation incomplete',
    ],
    ('plug cutout for microwave', 'JOINERY'): [
        'Cutout too small',
        'Cutout edges rough/unfinished',
        'Cutout misaligned with plug',
        'Cutout not made',
    ],

    # === FF&E ===
    ('installation', 'FF&E'): [
        'Item not installed',
        'Item not secured properly',
        'Item not level',
        'Installation incomplete',
    ],
    ('operation', 'FF&E'): [
        'Item not functioning correctly',
        'Item damaged',
        'Item needs adjustment',
    ],
    ('single bed', 'FF&E'): [
        'Bed frame damaged',
        'Bed frame scratched',
        'Bed frame not assembled correctly',
        'Bed frame unstable',
    ],
    ('mattress', 'FF&E'): [
        'Mattress not supplied',
        'Mattress stained/damaged',
        'Mattress wrong size',
    ],
    ('robe hook', 'FF&E'): [
        'Robe hook not installed',
        'Robe hook loose',
        'Robe hook position incorrect',
    ],
    ('desk chair', 'FF&E'): [
        'Chair not supplied',
        'Chair damaged',
        'Chair wheels not working',
        'Chair height adjustment faulty',
    ],
    ('towel rail', 'FF&E'): [
        'Towel rail not installed',
        'Towel rail loose',
        'Towel rail not level',
        'Towel rail scratched',
    ],
}

# Items to enrich (from database query)
items_to_enrich = [
    ('0a89cbd6', 'hinges', 'DOORS', 'KITCHEN'),
    ('78587133', 'finish', 'DOORS', 'KITCHEN'),
    ('17ff0a59', 'striker plate', 'DOORS', 'KITCHEN'),
    ('739d11f9', 'handle', 'DOORS', 'KITCHEN'),
    ('244e8c43', 'lockset - cylinder and thumb turn', 'DOORS', 'KITCHEN'),
    ('be712f2a', 'kickplate', 'DOORS', 'KITCHEN'),
    ('04bf84d7', 'master key', 'DOORS', 'KITCHEN'),
    ('e1357d91', 'door closer', 'DOORS', 'KITCHEN'),
    ('410c7b50', 'finish', 'DOORS', 'KITCHEN'),
    ('b149d8da', 'unit signage', 'DOORS', 'KITCHEN'),
    ('fda2e356', 'Face brick sill', 'DOORS', 'KITCHEN'),
    ('d149df25', 'soft joint between tile and brick', 'DOORS', 'KITCHEN'),
    ('7889a386', 'tile trim at window 1a', 'WALLS', 'KITCHEN'),
    ('1d0f508f', 'splash back wrap at sink', 'WALLS', 'KITCHEN'),
    ('637c7b25', 'tile trim at top and side', 'WALLS', 'KITCHEN'),
    ('5317757a', 'grout dove grey', 'WALLS', 'KITCHEN'),
    ('76477531', 'chipped/broken/hollow tiles', 'WALLS', 'KITCHEN'),
    ('82751f2d', 'hinges', 'WINDOWS', 'KITCHEN'),
    ('0b8e5fa2', 'operation', 'WINDOWS', 'KITCHEN'),
    ('bfc0e3ab', 'frame & coating', 'WINDOWS', 'KITCHEN'),
    ('0b7ae206', 'operation', 'WINDOWS', 'KITCHEN'),
    ('2cd5bdf0', 'burglar bars', 'WINDOWS', 'KITCHEN'),
    ('fa56c99f', 'Floor tile set out', 'FLOOR', 'KITCHEN'),
    ('71550213', 'paint-orchid bay', 'CEILING', 'KITCHEN'),
    ('6eb3af36', 'plaster recess', 'CEILING', 'KITCHEN'),
    ('6b89724d', 'fluorescent led x 2 bulbs', 'ELECTRICAL', 'KITCHEN'),
    ('13ec6997', 'fridge double plug', 'ELECTRICAL', 'KITCHEN'),
    ('1d0a879b', 'stove isolator', 'ELECTRICAL', 'KITCHEN'),
    ('92f6e79f', 'double plug below db', 'ELECTRICAL', 'KITCHEN'),
    ('2ec0e47b', 'double plug at W1a', 'ELECTRICAL', 'KITCHEN'),
    ('2073989a', 'single light switch by D1', 'ELECTRICAL', 'KITCHEN'),
    ('97cdacb1', 'operation', 'ELECTRICAL', 'KITCHEN'),
    ('6a8feed6', 'control panel', 'ELECTRICAL', 'KITCHEN'),
    ('d6dabbc6', 'installation', 'PLUMBING', 'KITCHEN'),
    ('4c301408', 'operation', 'PLUMBING', 'KITCHEN'),
    ('2e14552f', 'plugs', 'PLUMBING', 'KITCHEN'),
    ('3a377927', 'p-trap', 'PLUMBING', 'KITCHEN'),
    ('c66e451c', 'installation', 'PLUMBING', 'KITCHEN'),
    ('5c4e84c6', 'operation', 'PLUMBING', 'KITCHEN'),
    ('9eb9497b', 'stability plate', 'PLUMBING', 'KITCHEN'),
    ('4538a0a8', 'hot water', 'PLUMBING', 'KITCHEN'),
    ('e53474b8', 'cold water', 'PLUMBING', 'KITCHEN'),
    ('c64ad084', 'fixing to wall', 'JOINERY', 'KITCHEN'),
    ('2d37363a', 'finish', 'JOINERY', 'KITCHEN'),
    ('1b23f570', 'handles', 'JOINERY', 'KITCHEN'),
    ('0c881d18', 'top', 'JOINERY', 'KITCHEN'),
    ('78d8f95a', 'layout', 'JOINERY', 'KITCHEN'),
    ('09ca2f8d', 'fixing to wall', 'JOINERY', 'KITCHEN'),
    ('84813f65', 'finish', 'JOINERY', 'KITCHEN'),
    ('f0fc9699', 'layout', 'JOINERY', 'KITCHEN'),
    ('55191abe', 'fixing to wall', 'JOINERY', 'KITCHEN'),
    ('82218345', 'carcass', 'JOINERY', 'KITCHEN'),
    ('f2467f93', 'finish', 'JOINERY', 'KITCHEN'),
    ('b3b1880f', 'handles', 'JOINERY', 'KITCHEN'),
    ('2976f40b', 'top', 'JOINERY', 'KITCHEN'),
    ('3f5fe9dd', 'layout', 'JOINERY', 'KITCHEN'),
    ('543d889f', 'fixing to wall', 'JOINERY', 'KITCHEN'),
    ('b079da71', 'finish', 'JOINERY', 'KITCHEN'),
    ('0ae68663', 'hinges', 'JOINERY', 'KITCHEN'),
    ('215c2a34', 'handles', 'JOINERY', 'KITCHEN'),
    ('53b1dbfc', 'top', 'JOINERY', 'KITCHEN'),
    ('ee4fc5a2', 'layout', 'JOINERY', 'KITCHEN'),
    ('9d4b7503', 'top', 'JOINERY', 'KITCHEN'),
    ('3c16cdbc', 'fixing to wall', 'JOINERY', 'KITCHEN'),
    ('e96314c5', 'finish', 'JOINERY', 'KITCHEN'),
    ('20676181', 'hinges', 'JOINERY', 'KITCHEN'),
    ('a2d027f4', 'handles', 'JOINERY', 'KITCHEN'),
    ('8cdcb818', 'layout', 'JOINERY', 'KITCHEN'),
    ('c5931efd', 'fixing to wall', 'JOINERY', 'KITCHEN'),
    ('b35b9552', 'finish', 'JOINERY', 'KITCHEN'),
    ('8c4b0438', 'hinges', 'JOINERY', 'KITCHEN'),
    ('df9f5a7a', 'handles', 'JOINERY', 'KITCHEN'),
    ('103bccc2', 'layout', 'JOINERY', 'KITCHEN'),
    ('c011d8c9', 'fixing to wall', 'JOINERY', 'KITCHEN'),
    ('4ff599bf', 'hinges', 'JOINERY', 'KITCHEN'),
    ('8c97a66a', 'handles', 'JOINERY', 'KITCHEN'),
    ('57c5f6a0', 'plug cutout for microwave', 'JOINERY', 'KITCHEN'),
    ('b2dec45b', 'smooth plaster', 'WALLS', 'LOUNGE'),
    ('a46f716d', 'tile skirting', 'FLOOR', 'LOUNGE'),
    ('d7863733', 'paint-orchid bay', 'CEILING', 'LOUNGE'),
    ('a4163cb8', 'plaster recess', 'CEILING', 'LOUNGE'),
    ('ed852bc0', 'ceiling mounted light x 2 bulbs', 'ELECTRICAL', 'LOUNGE'),
    ('fa47bce5', 'double plug on 09 wall', 'ELECTRICAL', 'LOUNGE'),
    ('ee4e7f68', 'single light switch on 11 wall', 'ELECTRICAL', 'LOUNGE'),
    ('124015dc', 'installation', 'DOORS', 'BATHROOM'),
    ('a6939da2', 'operation', 'DOORS', 'BATHROOM'),
    ('25dda2a3', 'frame & coating', 'DOORS', 'BATHROOM'),
    ('051081c5', 'operation', 'WINDOWS', 'BATHROOM'),
    ('818a1716', 'chipped/broken/hollow tiles', 'FLOOR', 'BATHROOM'),
    ('d5c6a122', 'dark grey grout in shower', 'FLOOR', 'BATHROOM'),
    ('88b333f7', 'fall to trap', 'FLOOR', 'BATHROOM'),
    ('aa7d65dc', 'plaster recess', 'CEILING', 'BATHROOM'),
    ('1e31c282', 'installation', 'PLUMBING', 'BATHROOM'),
    ('a1515443', 'plug', 'PLUMBING', 'BATHROOM'),
    ('2cdb6424', 'p-trap', 'PLUMBING', 'BATHROOM'),
    ('b3cb1299', 'installation', 'PLUMBING', 'BATHROOM'),
    ('ac6bfae8', 'operation', 'PLUMBING', 'BATHROOM'),
    ('22b679a0', 'hot water', 'PLUMBING', 'BATHROOM'),
    ('8bb7d8ae', 'cold water', 'PLUMBING', 'BATHROOM'),
    ('9f1eb7ce', 'operation', 'PLUMBING', 'BATHROOM'),
    ('2879d87d', 'seat', 'PLUMBING', 'BATHROOM'),
    ('74fef16f', 'control panel', 'PLUMBING', 'BATHROOM'),
    ('4d5f2168', 'installation', 'PLUMBING', 'BATHROOM'),
    ('d4aab9e1', 'operation', 'PLUMBING', 'BATHROOM'),
    ('4670863e', 'hot water', 'PLUMBING', 'BATHROOM'),
    ('a1d687d8', 'cold water', 'PLUMBING', 'BATHROOM'),
    ('b131f27e', 'operation', 'PLUMBING', 'BATHROOM'),
    ('9da629f0', 'operation', 'PLUMBING', 'BATHROOM'),
    ('a0f9a29d', 'installation', 'PLUMBING', 'BATHROOM'),
    ('0a8a0ca3', 'operation', 'PLUMBING', 'BATHROOM'),
    ('a9e99c5e', 'installation', 'PLUMBING', 'BATHROOM'),
    ('52d96bc1', 'operation', 'PLUMBING', 'BATHROOM'),
    ('e5372c9d', 'installation', 'PLUMBING', 'BATHROOM'),
    ('d21c5759', 'operation', 'PLUMBING', 'BATHROOM'),
    ('eae7e6e1', 'hinges', 'DOORS', 'BEDROOM A'),
    ('cc84d464', 'lockset - cylinder and thumb turn', 'DOORS', 'BEDROOM A'),
    ('aae98150', 'key - A', 'DOORS', 'BEDROOM A'),
    ('196912e5', 'Signage', 'DOORS', 'BEDROOM A'),
    ('59a4040c', 'paint - Divina', 'WALLS', 'BEDROOM A'),
    ('4c05e67d', 'plaster recess at ceiling', 'WALLS', 'BEDROOM A'),
    ('f029f58b', 'burglar bars', 'WINDOWS', 'BEDROOM A'),
    ('4b7bbc57', 'sill', 'WINDOWS', 'BEDROOM A'),
    ('0ace260f', 'paint-orchid bay', 'CEILING', 'BEDROOM A'),
    ('73971770', 'paint - Divina', 'CEILING', 'BEDROOM A'),
    ('4033e53f', 'study desk light x 1 bulb', 'ELECTRICAL', 'BEDROOM A'),
    ('28999baf', 'combination plug wall 03', 'ELECTRICAL', 'BEDROOM A'),
    ('1aeff3ea', 'double light switch on wall 02', 'ELECTRICAL', 'BEDROOM A'),
    ('1ca36641', 'fixing to wall', 'JOINERY', 'BEDROOM A'),
    ('87c623cb', 'carcass', 'JOINERY', 'BEDROOM A'),
    ('eb55dc39', 'handles', 'JOINERY', 'BEDROOM A'),
    ('519d4580', 'installation', 'JOINERY', 'BEDROOM A'),
    ('468ece9d', 'finish', 'JOINERY', 'BEDROOM A'),
    ('bff8ca7f', 'layout', 'JOINERY', 'BEDROOM A'),
    ('d9b6f2ac', 'carcass', 'JOINERY', 'BEDROOM A'),
    ('fa7f85d7', 'finish', 'JOINERY', 'BEDROOM A'),
    ('dd6fc0d0', 'top', 'JOINERY', 'BEDROOM A'),
    ('34ea5535', 'installation', 'FF&E', 'BEDROOM A'),
    ('d1d59d05', 'operation', 'FF&E', 'BEDROOM A'),
    ('f0b24a5f', 'installation', 'FF&E', 'BEDROOM A'),
    ('15f1af2e', 'operation', 'FF&E', 'BEDROOM A'),
    ('b1f2960d', 'finished all round', 'DOORS', 'BEDROOM B'),
    ('31774738', 'hinges', 'DOORS', 'BEDROOM B'),
    ('8b80d8a5', 'paint on outside - Lemon Rind', 'DOORS', 'BEDROOM B'),
    ('f7d1845c', 'striker plate', 'DOORS', 'BEDROOM B'),
    ('80f75409', 'residence lock handle', 'DOORS', 'BEDROOM B'),
    ('1e45af79', 'lockset - cylinder and thumb turn', 'DOORS', 'BEDROOM B'),
    ('cea16d6c', 'key - B', 'DOORS', 'BEDROOM B'),
    ('a829adca', 'Signage', 'DOORS', 'BEDROOM B'),
    ('d1bfc830', 'smooth plaster', 'WALLS', 'BEDROOM B'),
    ('f2df64a6', 'paint - Lemon Rind', 'WALLS', 'BEDROOM B'),
    ('4605f30f', 'plaster recess at ceiling', 'WALLS', 'BEDROOM B'),
    ('0ff76a3f', 'gaskets', 'WINDOWS', 'BEDROOM B'),
    ('d58ea077', 'operation', 'WINDOWS', 'BEDROOM B'),
    ('5521401d', 'burglar bars', 'WINDOWS', 'BEDROOM B'),
    ('b389dfc2', 'paint-orchid bay', 'CEILING', 'BEDROOM B'),
    ('205e2898', 'paint - Lemon Rind', 'CEILING', 'BEDROOM B'),
    ('e2fd6318', 'study desk light x 1 bulb', 'ELECTRICAL', 'BEDROOM B'),
    ('a11aff40', 'panel heater plug wall 07', 'ELECTRICAL', 'BEDROOM B'),
    ('a21624c2', 'combination plug wall 05', 'ELECTRICAL', 'BEDROOM B'),
    ('de73d950', 'double light switch on wall 08', 'ELECTRICAL', 'BEDROOM B'),
    ('3b8b3f96', 'fixing to wall', 'JOINERY', 'BEDROOM B'),
    ('15dc31bd', 'handles', 'JOINERY', 'BEDROOM B'),
    ('7b3e816b', 'installation', 'JOINERY', 'BEDROOM B'),
    ('f19b1e13', 'layout', 'JOINERY', 'BEDROOM B'),
    ('efe27d9d', 'carcass', 'JOINERY', 'BEDROOM B'),
    ('43f70971', 'finish', 'JOINERY', 'BEDROOM B'),
    ('05790528', 'top', 'JOINERY', 'BEDROOM B'),
    ('9359dd96', 'installation', 'FF&E', 'BEDROOM B'),
    ('1f2fe184', 'operation', 'FF&E', 'BEDROOM B'),
    ('220f697a', 'installation', 'FF&E', 'BEDROOM B'),
    ('2189cff1', 'operation', 'FF&E', 'BEDROOM B'),
    ('e833bf33', 'hinges', 'DOORS', 'BEDROOM C'),
    ('24dfa887', 'paint on outside - Glorious gold', 'DOORS', 'BEDROOM C'),
    ('4c0f7fbe', 'lockset - cylinder and thumb turn', 'DOORS', 'BEDROOM C'),
    ('d81f99e9', 'key - C', 'DOORS', 'BEDROOM C'),
    ('dad5b52a', 'Signage', 'DOORS', 'BEDROOM C'),
    ('1fae2eac', 'frame & coating', 'WINDOWS', 'BEDROOM C'),
    ('13960def', 'gaskets', 'WINDOWS', 'BEDROOM C'),
    ('4bae57dc', 'operation', 'WINDOWS', 'BEDROOM C'),
    ('b3d74254', 'burglar bars', 'WINDOWS', 'BEDROOM C'),
    ('85620ac4', 'chipped/broken/hollow tiles', 'FLOOR', 'BEDROOM C'),
    ('f34b4fe9', 'grout dove grey', 'FLOOR', 'BEDROOM C'),
    ('6a0771ae', 'tile skirting', 'FLOOR', 'BEDROOM C'),
    ('75b4fde3', 'ceiling mounted light x 1 bulbs', 'ELECTRICAL', 'BEDROOM C'),
    ('5be0a265', 'study desk light x 1 bulb', 'ELECTRICAL', 'BEDROOM C'),
    ('ef4935cb', 'panel heater plug wall 21', 'ELECTRICAL', 'BEDROOM C'),
    ('5cee2550', 'combination plug wall 22', 'ELECTRICAL', 'BEDROOM C'),
    ('c57a6bb2', 'double light switch on wall 24', 'ELECTRICAL', 'BEDROOM C'),
    ('3c88e688', 'fixing to wall', 'JOINERY', 'BEDROOM C'),
    ('981e4097', 'carcass', 'JOINERY', 'BEDROOM C'),
    ('4e25adea', 'finish', 'JOINERY', 'BEDROOM C'),
    ('f3578740', 'handles', 'JOINERY', 'BEDROOM C'),
    ('0b929eb3', 'installation', 'JOINERY', 'BEDROOM C'),
    ('2f006892', 'finish', 'JOINERY', 'BEDROOM C'),
    ('9df93678', 'layout', 'JOINERY', 'BEDROOM C'),
    ('6ba3e495', 'carcass', 'JOINERY', 'BEDROOM C'),
    ('8cf30e13', 'finish', 'JOINERY', 'BEDROOM C'),
    ('c4a5aa6b', 'top', 'JOINERY', 'BEDROOM C'),
    ('69c1cf1c', 'single bed', 'FF&E', 'BEDROOM C'),
    ('2bd8271a', 'mattress', 'FF&E', 'BEDROOM C'),
    ('f3c554ab', 'robe hook', 'FF&E', 'BEDROOM C'),
    ('35352a04', 'desk chair', 'FF&E', 'BEDROOM C'),
    ('fe1f4b2d', 'towel rail', 'FF&E', 'BEDROOM C'),
    ('ecb87392', 'installation', 'FF&E', 'BEDROOM C'),
    ('7b76217f', 'operation', 'FF&E', 'BEDROOM C'),
    ('5249a8fd', 'installation', 'FF&E', 'BEDROOM C'),
    ('dc8d6550', 'operation', 'FF&E', 'BEDROOM C'),
    ('c0183fae', 'hinges', 'DOORS', 'BEDROOM D'),
    ('3b18b7d5', 'paint on outside - Yellow balloon', 'DOORS', 'BEDROOM D'),
    ('c2751cbe', 'striker plate', 'DOORS', 'BEDROOM D'),
    ('9d6fe4a5', 'residence lock handle', 'DOORS', 'BEDROOM D'),
    ('bb4b4360', 'lockset - cylinder and thumb turn', 'DOORS', 'BEDROOM D'),
    ('6f7226bd', 'key - D', 'DOORS', 'BEDROOM D'),
    ('05c84b01', 'smooth plaster', 'WALLS', 'BEDROOM D'),
    ('bd6a61c0', 'paint - Yellow balloon', 'WALLS', 'BEDROOM D'),
    ('0a0fb9b6', 'plaster recess at ceiling', 'WALLS', 'BEDROOM D'),
    ('4a354d81', 'frame & coating', 'WINDOWS', 'BEDROOM D'),
    ('bb5eae25', 'gaskets', 'WINDOWS', 'BEDROOM D'),
    ('bc867a0a', 'operation', 'WINDOWS', 'BEDROOM D'),
    ('207492fc', 'burglar bars', 'WINDOWS', 'BEDROOM D'),
    ('956b6837', 'grout dove grey', 'FLOOR', 'BEDROOM D'),
    ('a39a8899', 'tile skirting', 'FLOOR', 'BEDROOM D'),
    ('a709718f', 'paint - Glorious gold', 'CEILING', 'BEDROOM D'),
    ('00ce4ba3', 'ceiling mounted light x 1 bulbs', 'ELECTRICAL', 'BEDROOM D'),
    ('b1b7e7ec', 'study desk light x 1 bulb', 'ELECTRICAL', 'BEDROOM D'),
    ('700c338e', 'panel heater plug wall 20', 'ELECTRICAL', 'BEDROOM D'),
    ('afe6b938', 'combination plug wall 19', 'ELECTRICAL', 'BEDROOM D'),
    ('5b96638f', 'double light switch on wall 17', 'ELECTRICAL', 'BEDROOM D'),
    ('c874f059', 'fixing to wall', 'JOINERY', 'BEDROOM D'),
    ('263b99ba', 'carcass', 'JOINERY', 'BEDROOM D'),
    ('ca497a99', 'hinges', 'JOINERY', 'BEDROOM D'),
    ('cd7d1627', 'handles', 'JOINERY', 'BEDROOM D'),
    ('f653cf83', 'installation', 'JOINERY', 'BEDROOM D'),
    ('135828f3', 'finish', 'JOINERY', 'BEDROOM D'),
    ('d052cb8e', 'layout', 'JOINERY', 'BEDROOM D'),
    ('703b89ce', 'carcass', 'JOINERY', 'BEDROOM D'),
    ('b30c2d79', 'top', 'JOINERY', 'BEDROOM D'),
    ('151d2b2e', 'installation', 'FF&E', 'BEDROOM D'),
    ('68ad5ceb', 'operation', 'FF&E', 'BEDROOM D'),
    ('e4104535', 'installation', 'FF&E', 'BEDROOM D'),
    ('5d30fb30', 'operation', 'FF&E', 'BEDROOM D'),
]

inserted = 0
skipped = 0
not_mapped = []

for item_id, item_desc, category, area in items_to_enrich:
    key = (item_desc.lower(), category)
    
    defects = ITEM_DEFECTS.get(key)
    if not defects:
        not_mapped.append(f'{area} | {category} | {item_desc}')
        continue
    
    for desc in defects:
        lib_id = str(uuid.uuid4())[:8]
        try:
            cur.execute("""
                INSERT INTO defect_library (id, tenant_id, category_name, item_template_id, description, usage_count, is_system, created_at)
                VALUES (?, ?, ?, ?, ?, 0, 1, ?)
            """, (lib_id, TENANT, category, item_id, desc, now))
            inserted += 1
        except Exception as e:
            skipped += 1

conn.commit()
conn.close()

print(f'ENRICHMENT COMPLETE')
print(f'  Inserted: {inserted} item-specific suggestions')
print(f'  Skipped: {skipped}')
print(f'  Not mapped: {len(not_mapped)}')
if not_mapped:
    print(f'\nItems without mapping (will use category fallbacks):')
    for nm in not_mapped:
        print(f'  {nm}')
